language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "python -m unittest discover"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
